# Generated by Django 5.2 on 2025-05-18 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0002_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinesale',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
