# Generated by Django 5.2 on 2025-05-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0009_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='consultation_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
